const ilusInfo = [

    {
        name: 'Astro Glitter',
        realName: '',
        url: 'astro-glitter',
        contact: {
            ig: 'glitter.illustration',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'List.retamal@gmail.com',
        },
        images: ['a1', 'a2', 'a3', 'a4'],
        location: 'IV Región, Coquimbo',
        bio: 'Mi trabajo consiste principalmente en realizar ilustraciones digitales, las temáticas que abordo son el misticismo, feminidad, veganismo y la psicodelia, estas ilustraciones posteriormente las incorporo en diversos productos y papelería.'
    }, 

    {
        name: 'Blue Straycatt',
        realName: 'Gabriela Contreras',
        url: 'blue-straycatt',
        contact: {
            ig: 'blue_straycatt_art',
            fb: 'blue.straycatt.art',
            twitter: 'bluestraycatart',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'gabriela95_contreras@hotmail.com',
        },
        images: ['b1', 'b2', 'b3', 'b4'],
        location: 'IV Región, Coquimbo',
        bio: 'Me gusta mucho basarme en el género de fantasía oscura, donde puedo buscar muchas posibilidades para explorar conceptos e ideas con un enfoque más personal, a través de tinta y achurado, busco valorizar luces, sombras y detalles al máximo.',
    },

    {
        name: 'Camellia Liz',
        realName: 'Camila Herrera',
        url: 'camellia-liz',
        contact: {
            ig: 'camellia.liz',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: 'channel/UCrjJGDr9qHlWMdGDmRlvMlw',
            web: '',
            mail: 'camihlatournerie@gmail.com',
        },
        images: ['c1', 'c2', 'c3', 'c4'],
        location: 'IV Región, Coquimbo',
        bio: 'Artista e ilustradora dedicada principalmente al trabajo con medios tradicionales como la acuarela. <br><br>Se especializa en ilustraciones semi-realistas con temáticas delicadas y femeninas de  tono nostálgico, cálido y emocional. <br><br>Su trabajo toma inspiración principalmente de los cuentos de hadas, la literatura clásica, la magia, la naturaleza, las emociones humanas  y  las diferentes culturas del mundo,  siempre desde un ángulo distintivamente emotivo, femenino y lleno de realismo mágico.',
    },

    {
        name: 'Camipepe',
        realName: 'José Flores y Camila Olivares',
        url: 'camipepe',
            contact: {
            ig: 'camiipepe',
            fb: '',
            twitter: '',
            behance: 'Camipepe',
            tiktok: '',
            youtube: '',
            web: 'https://camipepe.com/',
            mail: 'camiiipepe@gmail.com',
        },
        images: ['d1', 'd2', 'd3'],
        location: 'IV Región, La Serena',
        bio: 'Somos “Camipepe” Camila Olivares (Cami) y José Flores (Pepe). Nos dedicamos a la ilustración de forma independiente. Trabajamos juntos de hace 5 años, luego de salir de la carrera de Diseño Gráfico. <br><br> En nuestro trabajo nos gusta usar colores vivos y formas simples, usamos una técnica digital que nos permite tener ilustraciones versátiles. Nuestras temáticas favorita son los animales, la cultura, la naturaleza y las cosas cotidianas. <br><br>Tenemos dos lineas de trabajo: proyectos personales, donde aplicamos nuestras ilustraciones a distintos productos y Las ilustraciones que realizamos a pedido. También nos gusta enseñar y regularmente impartimos talleres de ilustración para niños y jóvenes.',
    },

    {
        name: 'CatAna',
        realName: '',
        url: 'catana',
            contact: {
            ig: 'c_a_t_a_n_a',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'a.gutierrezuribe@gmail.com',
        },
        images: ['e1', 'e2', 'e3'],
        location: 'IV Región, La Serena',
        bio: 'Mi trabajo combina cotidianidad con el imaginario de elementos surrealistas y espaciales, inspirados en la cultura pop y/o la contingencia social.',
    },

    {
        name: 'Collarcitos',
        realName: 'Romina Villegas Peña',
        url: 'collarcitos',
            contact: {
            ig: 'collarcitosrv',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'collarcitos@gmail.com',
        },
        images: ['f1', 'f2', 'f3', 'f4'],
        location: 'V Región, La Serena',
        bio: 'Totalmente tradicional: acuarela, marcadores, tinta china, tiralíneas, entre estos materiales me muevo. <br><br>Todo muy orgánico, animales, vegetación y algo de cultura popular es lo que pueden ver en mis trabajos, y por supuesto que también algún guiño a la contingencia.',
    },

    {
        name: 'Cris Crowfin',
        realName: 'Cristián Patricio Marin Flores',
        url: 'cris-crowfin',
            contact: {
            ig: 'crowfin_art',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'cristian.p.marin@gmail.com',
        },
        images: ['g1', 'g2', 'g3'],
        location: 'IV Región, Coquimbo',
        bio: 'Mi nombre es Cristian Marin, alias “cris crowfin”, y soy un aficionado a la ilustración desde siempre. <br><br>Teniendo un estilo básico en ilustración tradicional, con clara influencia en el manga japonés, gusto de dibujar fan arts de mis personajes e historias favoritas. Aun así, mi creatividad no deja de inspirarme y muchas veces creo mis propios diseños. <br><br>Actualmente sigo en camino por mejorar mi estilo, aprendiendo técnicas digitales para incorporar a mis creaciones. Todo con el objetivo de realizar grandes proyectos, trabajar con otros grandes artistas y profesionalizar mi arte.<',
    },

    {
        name: 'Drömmer',
        realName: 'Gabriela Elgueta',
        url: 'drommer',
            contact: {
            ig: 'drommer_art',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'drommer.art@gmail.com',
        },
        images: ['h1', 'h2', 'h3', 'h4'],
        location: 'IV Región, La Serena',
        bio: 'Mi trabajo se basa en su mayoría en el dibujo digital, centrándome en el realismo a la hora de ponerme a trabajar. <br /><br />Me gusta mucho experimentar con colores fuertes y con alto contraste, creando una paleta única en cada una de mis obras. Me encanta la fantasía y el folclore japonés, por lo que estos elementos los utilizo mucho cuando comienzo a dibujar y es algo que podrás encontrar fácilmente en mi galería.',
    },

    {
        name: 'E.vincent.V',
        realName: 'Vincent Gedeon Gatica Espinoza',
        url: 'evincentv',
            contact: {
            ig: 'e.vincent.v',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'e.vincentdiseno@gmail.com',
        },
        images: ['i1', 'i2', 'i3', 'i4'],
        location: 'IV Región, Coquimbo',
        bio: 'Me dedico a experimentar con diversas ilustraciones y cómics tratando de darle una vuelta creativa a las cosas que me rodean, mediante esto puedo encontrar nuevas maneras de conocer y entender, a veces se logra otras no tanto...',
    },

    {
        name: 'Eline1three',
        realName: 'Hellen Elizabeth Quiñones Maluenda',
        url: 'eline1three',
            contact: {
            ig: 'enile1three',
            fb: '',
            twitter: 'enile1three',
            behance: '',
            tiktok: '@eline1three',
            youtube: '',
            web: '',
            mail: 'eline1three@gmail.com',
        },
        images: ['j1', 'j2', 'j3'],
        location: 'IV Región, Coquimbo',
        bio: 'Hello! Mi nombre es Eline y soy ilustradora digital y tradicional. Mi fuerte es el estilo anime y me gusta dibujar personajes de mis series favoritas. <br><br>También soy riggeadora de vtubers, básicamente creo personajes que puedan seguir el movimiento de la cara, muchas gracias por leer!',
    },

    {
        name: 'elMeNeSe',
        realName: 'Iván Andrés Jorquera Olivares',
        url: 'elmenese',
            contact: {
            ig: 'elmenese',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'ivanjorquera.o@gmail.com',
        },
        images: ['k1', 'k2', 'k3'],
        location: 'IV Región, La Serena',
        bio: 'Gran Parte de mi trabajo está enfocado en el Arte urbano, ya que me dedico a realizar graffiti desde los 13 años. <br><br>En la actualidad realizo proyectos de arte público, rescate del patrimonio intangible a través de murales. Soy el productor y ejecutor de 2 versiones del proyecto colores de mi barrio, creado por la gestión territorial del departamento de cultura de Coquimbo y este año se planifica la primera Ruta de Murales Patrimoniales de la Región. <br><br>Individualmente estoy trabajando en una serie de cuadros donde mezclo la naturaleza con los elementos más urbanos, que tienen estrecha relación con el graffiti, como tag, caps y latas de aerosol, creando composiciones que contrastan pero que se pueden parecer paisajes cotidianos de nuestras ciudades.',
    },

    {
        name: 'Neehre',
        realName: '',
        url: 'neehre',
            contact: {
            ig: 'neeh_re',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'rene.f.arayaramirez@gmail.com',
        },
        images: ['l1', 'l2', 'l3', 'l4'],
        location: 'IV Región, La Serena',
        bio: 'Autodidacta. Con un estilo por definir, pero caracterizado por colores vibrantes y la creación constante de personajes. Experimentando entre los digital y lo análogo. <br><br>Inspirado principalmente en lo surrealista, recurriendo a elementos del ambiente, como nubes, fuego y hojas, junto a elementos de diversos seres vivos y seres humano compartiendo elementos, dando paso a nuevas formas.',
    },

    {
        name: 'Niño Pan',
        realName: '',
        url: 'niño-pan',
            contact: {
            ig: 'algundiazyueng',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'diazyueng@gmail.com',
        },
        images: ['m1', 'm2', 'm3'],
        location: 'IV Región, La Serena',
        bio: 'Mi trabajo en la parte personal está enfocado principalmente en dibujar cosas cotidianas y dudas existenciales.',
    },

    {
        name: 'Ojus Pocus',
        realName: '',
        url: 'ojus-pocus',
            contact: {
            ig: 'ojus___',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'ojuspocus1@gmail.com',
        },
        images: ['n1', 'n2', 'n3'],
        location: 'IV Región, Ovalle',
        bio: 'Soy Licenciada en diseño y docente de artes, en mis manos siempre tengo lápices o plumones y ahora el iPad que me abrió un mundo de posibilidades que complemento con illustraitor y muchos tutoriales. <br><br>Soy amante de la vegetación y las energías, casi todo mi trabajo se basa en eso y me libera bastante. Trato de unir el diseño y la docencia constantemente y adquirir más conocimiento día a día.',
    },

    {
        name: 'Prrr Miaow',
        realName: '',
        url: 'prrr-miaow',
            contact: {
            ig: 'prrr.miaow',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'Karenvalen.diseno@gmail.com',
        },
        images: ['o1', 'o2', 'o3'],
        location: 'IV Región, La Serena',
        bio: 'Ilustraciónes principalmente de animales y también fanart, con estilo simple y kawaii, todo esto aplicado en diversos productos, como chapitas, calendarios, libretas, stickers, posters, espejos marca paginas y más, existe gran variedad de diseños y productos.',
    },

    {
        name: 'Sofiniscus',
        realName: 'Sofía Marambio Cortés',
        url: 'sofiniscus',
            contact: {
            ig: 'sofi_niscus',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'sofiniscusilustraciones@gmail.com',
        },
        images: ['p1', 'p2', 'p3'],
        location: 'IV Región, La Serena',
        bio: 'Mi nombre es Sofía Marambio, soy estudiante universitaria e ilustradora aficionada. Mis ilustraciones son generalmente personas del sexo femenino, ya que me gusta plasmar la verdadera belleza que nace desde lo imperfecto, y que cada rasgo que te hace diferente a los demás te hace única. <br /><br />Además también me gusta ilustrar mascotas y animalitos en general, siento que en cada retrato puedo plasmar la pureza y amor que demuestras estos seres lo cual me hace muy feliz. <br /><br />Actualmente estoy experimentando con nuevas técnicas y mejorando las que ya dominaba, espero en un futuro mi trabajo llegue a muchas personas y al observarlo puedan sentir lo que hay detrás de cada una de mis obras.',
    },

    {
        name: 'Sunmorales',
        realName: '',
        url: 'sunmorales',
            contact: {
            ig: 'sunmorales',
            fb: '',
            twitter: '',
            behance: 'sunmorales',
            tiktok: 'ZMe6k1Yoe',
            youtube: 'channel/UCi9rnKd4G7YlCiXzedEXqvw',
            web: 'https://www.sunmorales.com/',
            mail: 'sunmorales35@gmail.com',
        },
        images: ['q1', 'q2', 'q3'],
        location: 'IV Región, La Serena',
        bio: 'Ilustradora Profesional, fotógrafa, audiovisual, entusiasta de los gatos y los comics.<br /><br /> Mi forma favorita de comunicación es la imagen. Desde que tengo memoria me ha gustado contar historias y es a través del comic es que he encontrado mi medio para hacerlo, conociendo en internet una comunidad de humanos que aman los gatos tanto como yo. <br /><br />He trabajado en diferentes proyectos y mi enfoque esta en redes sociales, donde comparto mayoritariamente mis comics y videos. También tengo una línea de ilustraciones, generalmente de corte fantástico, con animales gigantes, seres antropomorfos o gatitos flotando en el espacio. Entre mis temas más comunes puedes encontrar la cotidianidad, los gatos, salud mental y la vida en general. Espero que te guste mi trabajo!',
    },

    {
        name: 'Tigre Maltés',
        realName: 'Alonso Martínez Muñoz',
        url: 'tigre-maltes',
            contact: {
            ig: 'tigre_maltes',
            fb: '',
            twitter: '',
            behance: '',
            tiktok: '',
            youtube: '',
            web: '',
            mail: 'alonsomartinez07@gmail.com',
        },
        images: ['r1', 'r2', 'r3'],
        location: 'IV Región, Coquimbo',
        bio: 'Desarrollo del arte gráfico, inspirado en la estética del cartelismo y los cómics, para generar una narrativa visual propia.',
    },
]

export default ilusInfo