name: Merge release to main on schedule

on:
  schedule:
    - cron: '25 16 3 6 *' # 3 de junio a las 12:25 CLT (16:25 UTC)
  workflow_dispatch:

jobs:
  merge-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: release/convocatoria-2025

      - name: Merge release/convocatoria-2025 into main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const base = "main";
            const head = "release/convocatoria-2025";

            // Create a pull request
            const { data: pr } = await github.rest.pulls.create({
              owner,
              repo,
              title: "Auto-merge release/convocatoria-2025 into main",
              head,
              base,
              body: "Este merge fue realizado automáticamente por GitHub Actions el 3 de junio de 2025 a las 12:25 CLT.",
              maintainer_can_modify: true
            });

            // Merge the pull request
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pr.number,
              merge_method: "merge"
            });

            console.log(`Merged PR #${pr.number}`);
